version: '3.8'
services:
  postgres:
    image: postgres:13.5
    restart: always
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres

  api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: always
    depends_on:
      - postgres
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - ./generatedFiles/:/app/generatedFiles
      - ./uploadedFiles/:/app/uploadedFiles

volumes:
  postgres:
